### ISSUE TITLE
大佬 你blog上那个网速显示怎么弄的？

### ISSUE THREAD

**Issue by DreamMaoMao** [Isoheptane/dotfiles#1]
![image](https://github.com/Isoheptane/dotfiles/assets/30348075/2bfe729c-b396-41e7-b844-529b90b2c29d)

**Comment by DreamMaoMao** [comment]
打扰了  有个变量可以设置的

**Comment by greenhandzdl** [comment]
啊？你们图标为什么是正常的，怎么设置的啊

**Comment by Isoheptane** [comment]
> 啊？你们图标为什么是正常的，怎么设置的啊

這個是 Fone Awesome 字體啦
